tables = [
    "alport_clinical_picture",
    "biomarker",
    "biomarker_barcode",
    "biomarker_result",
    "biomarker_sample",
    "cohort",
    "cohort_diagnosis",
    "cohort_patient",
    "consent",
    "consultant",
    "country",
    "country_ethnicity",
    "country_nationality",
    "current_medication",
    "classification_code",
    "data_source",
    "diagnosis",
    "dialysis",
    "drug",
    "drug_group",
    "ethnicity",
    "family_history",
    "family_history_relation",
    "fetal_ultrasound",
    "fuan_clinical_picture",
    "fuan_clinical_picture_relative",
    "genetics",
    "hospital_consultant",
]

enums = {"cohortdiagnosistypeenum": ("primary", "secondary")}
